In [1]:
import pandas as pd

In [3]:
df =  pd.read_csv('./files/pmqc_2016_02.csv', sep =';', encoding = 'iso-8859-1');

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36360 entries, 0 to 36359
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   DataColeta        36360 non-null  object
 1   IdNumeric         36360 non-null  int64
 2   GrupoProduto      36360 non-null  object
 3   Produto           36360 non-null  object
 4   RazaoSocialPosto  36360 non-null  object
 5   CnpjPosto         36360 non-null  object
 6   Distribuidora     36360 non-null  object
 7   EndereÃ§o         36360 non-null  object
 8   Complemento       13418 non-null  object
 9   Bairro            36321 non-null  object
 10  MunicÃ­pio        36360 non-null  object
 11  Latitude          15430 non-null  float64
 12  Longitude         15430 non-null  float64
 13  Uf                36360 non-null  object
 14  RegiaoPolitica    36360 non-null  object
 15  Ensaio            36360 non-null  object
 16  Resultado         36360 non-null  object
 17  UnidadeEnsaio     25203 non-null  object
 18  Conforme          36360 non-null  object
dtypes: float64(2), int64(1), object(16)
memory usage: 5.3+ MB

In [13]:
# Dados foram obtidos em https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos/arquivos/pmqc/2016 (... até 2023)
# Nomes dos arquivos foram padronizados em  https://www.facom.ufu.br/~albertini/dados/pmqc/pmqc_AAAA_MM.csv

# De 2016/01 a 2018/12 usa formato https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos/arquivos/pmqc/2016/pmqc_AAAA_MM.[json,csv]
# https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos/arquivos/pmqc/2016/pmqc_2016_01.csv
# De 2019/01 a 2022/06 usa
# https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos/arquivos/pmqc/2019/2019-01-pmqc.csv
#https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos/arquivos/pmqc/2022/2022-06-pmqc.csv
# De 2022/07 a 2022/12 usa
#https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos/arquivos/pmqc/2022/pmqc_2022_07.csv
# De 2023/01 a 2023/11 usa
#https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos/arquivos/pmqc/2023/pmqc-01.csv
#https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos/arquivos/pmqc/2023/pmqc-11.csv

import pandas as pd

pmqc = pd.DataFrame()

for ano in range(2022, 2023): # existem dados de 01/2016 a 11/2023
  for mes in range(1, 13):

    if mes < 10:
      mes = '0'+str(mes)

    url = "https://www.facom.ufu.br/~albertini/dados/pmqc/pmqc_"+str(ano)+"_"+str(mes)+".csv"
    if ano == 2023 and mes == 22: break  # ainda não existe esse arquivo

    pmqc = pd.concat( [pmqc, pd.read_csv(url, sep = ';')] )
    print(pmqc.shape)

(41966, 19)
(82268, 19)
(129144, 19)
(162988, 19)
(199030, 19)
(242359, 19)
(316741, 19)
(383901, 19)
(461472, 19)
(529025, 19)
(596838, 19)
(669776, 19)

In [15]:
pmqc.info()

       DataColeta  IdNumeric GrupoProduto                 Produto  \
0      2022-01-18     729796     Gasolina        GASOLINA C COMUM
1      2022-01-18     729796     Gasolina        GASOLINA C COMUM
2      2022-01-18     729796     Gasolina        GASOLINA C COMUM
3      2022-01-18     729796     Gasolina        GASOLINA C COMUM
4      2022-01-18     729796     Gasolina        GASOLINA C COMUM
...           ...        ...          ...                     ...
72933  2022-12-27     786810       Etanol  ETANOL HIDRATADO COMUM
72934  2022-12-27     786810       Etanol  ETANOL HIDRATADO COMUM
72935  2022-12-27     786810       Etanol  ETANOL HIDRATADO COMUM
72936  2022-12-27     786810       Etanol  ETANOL HIDRATADO COMUM
72937  2022-12-27     786805       Etanol  ETANOL HIDRATADO COMUM

                            RazaoSocialPosto           CnpjPosto  \
0                   AUTO POSTO ESTREITO LTDA  11.068.671/0002-91
1                   AUTO POSTO ESTREITO LTDA  11.068.671/0002-91
2                   AUTO POSTO ESTREITO LTDA  11.068.671/0002-91
3                   AUTO POSTO ESTREITO LTDA  11.068.671/0002-91
4                   AUTO POSTO ESTREITO LTDA  11.068.671/0002-91
...                                      ...                 ...
72933          SIQUEIRA BATISTA E BISPO LTDA  02.874.397/0001-76
72934          SIQUEIRA BATISTA E BISPO LTDA  02.874.397/0001-76
72935          SIQUEIRA BATISTA E BISPO LTDA  02.874.397/0001-76
72936          SIQUEIRA BATISTA E BISPO LTDA  02.874.397/0001-76
72937  ROMEIROS 1 COMERCIO DE  PETROLEO LTDA  33.211.167/0001-50

          Distribuidora              Endereço  \
0      Não Identificada  AVENIDA MARANHÃO,744
1      Não Identificada  AVENIDA MARANHÃO,744
2      Não Identificada  AVENIDA MARANHÃO,744
3      Não Identificada  AVENIDA MARANHÃO,744
4      Não Identificada  AVENIDA MARANHÃO,744
...                 ...                   ...
72933   BANDEIRA BRANCA       AVENIDA DO POVO
72934   BANDEIRA BRANCA       AVENIDA DO POVO
72935   BANDEIRA BRANCA       AVENIDA DO POVO
72936   BANDEIRA BRANCA       AVENIDA DO POVO
72937   BANDEIRA BRANCA     RUA MONTE CASTELO

                               Complemento             Bairro Município  \
0                                      NaN             CENTRO  ESTREITO
1                                      NaN             CENTRO  ESTREITO
2                                      NaN             CENTRO  ESTREITO
3                                      NaN             CENTRO  ESTREITO
4                                      NaN             CENTRO  ESTREITO
...                                    ...                ...       ...
72933                                    0       VILA MUTIRAO   GOIANIA
72934                                    0       VILA MUTIRAO   GOIANIA
72935                                    0       VILA MUTIRAO   GOIANIA
72936                                    0       VILA MUTIRAO   GOIANIA
72937  QUADRA104                 LOTE  1/3  JARDIM PETROPOLIS   GOIANIA

        Latitude  Longitude  Uf RegiaoPolitica                   Ensaio  \
0            NaN        NaN  MA       NORDESTE                  Aspecto
1            NaN        NaN  MA       NORDESTE                      Cor
2            NaN        NaN  MA       NORDESTE  Massa Específica a 20°C
3            NaN        NaN  MA       NORDESTE           Teor de Etanol
4            NaN        NaN  MA       NORDESTE         Destilação - 10%
...          ...        ...  ..            ...                      ...
72933 -16.613464 -49.343612  GO   CENTRO OESTE   Condutividade Elétrica
72934 -16.613464 -49.343612  GO   CENTRO OESTE  Massa Específica a 20°C
72935 -16.613464 -49.343612  GO   CENTRO OESTE           Teor Alcoólico
72936 -16.613464 -49.343612  GO   CENTRO OESTE          Teor de Metanol
72937 -16.659822 -49.342718  GO   CENTRO OESTE  Massa Específica a 20°C

                                 Resultado UnidadeEnsaio Conforme
0      Límpido e isento de impurezas (LII)           NaN      Sim
1                                  Amarelo           NaN      Sim
2                                    739.3         kg/m³      Sim
3                                       27      % volume      Sim
4                                     53.4            °C      Sim
...                                    ...           ...      ...
72933                                  152          µS/m      Sim
72934                                810.2         kg/m³      Sim
72935                                 92.8       % massa      Sim
72936                                  0.0      % volume      Sim
72937                                810.3         kg/m³      Sim

[669776 rows x 19 columns]

In [18]:
pmqc.head()

,DataColeta,IdNumeric,GrupoProduto,Produto,RazaoSocialPosto,CnpjPosto,Distribuidora,Endereço,Complemento,Bairro,Município,Latitude,Longitude,Uf,RegiaoPolitica,Ensaio,Resultado,UnidadeEnsaio,Conforme
0,2022-01-18,729796,Gasolina,GASOLINA C COMUM,AUTO POSTO ESTREITO LTDA,11.068.671/0002-91,Não Identificada,"AVENIDA MARANHÃO,744",NaN,CENTRO,ESTREITO,NaN,NaN,MA,NORDESTE,Aspecto,Límpido e isento de impurezas (LII),NaN,Sim
1,2022-01-18,729796,Gasolina,GASOLINA C COMUM,AUTO POSTO ESTREITO LTDA,11.068.671/0002-91,Não Identificada,"AVENIDA MARANHÃO,744",NaN,CENTRO,ESTREITO,NaN,NaN,MA,NORDESTE,Cor,Amarelo,NaN,Sim
2,2022-01-18,729796,Gasolina,GASOLINA C COMUM,AUTO POSTO ESTREITO LTDA,11.068.671/0002-91,Não Identificada,"AVENIDA MARANHÃO,744",NaN,CENTRO,ESTREITO,NaN,NaN,MA,NORDESTE,Massa Específica a 20°C,739.3,kg/m³,Sim
3,2022-01-18,729796,Gasolina,GASOLINA C COMUM,AUTO POSTO ESTREITO LTDA,11.068.671/0002-91,Não Identificada,"AVENIDA MARANHÃO,744",NaN,CENTRO,ESTREITO,NaN,NaN,MA,NORDESTE,Teor de Etanol,27,% volume,Sim
4,2022-01-18,729796,Gasolina,GASOLINA C COMUM,AUTO POSTO ESTREITO LTDA,11.068.671/0002-91,Não Identificada,"AVENIDA MARANHÃO,744",NaN,CENTRO,ESTREITO,NaN,NaN,MA,NORDESTE,Destilação - 10%,53.4,°C,Sim

In [23]:
combustiveis_distintos = pmqc['GrupoProduto'].drop_duplicates()

print("Combustíveis distintos: \n", combustiveis_distintos)

Combustíveis distintos:
 0        Gasolina
9     Óleo Diesel
27         Etanol
Name: GrupoProduto, dtype: object

In [25]:
status_conformidade = pmqc['Conforme'].drop_duplicates()

print("Status: \n", status_conformidade)

Status:
 0       Sim
2367    Não
Name: Conforme, dtype: object

In [27]:
import re

def normalizar_string(s):
    # Remove caracteres especiais usando expressão regular
    s_sem_especiais = re.sub(r'[^a-zA-Z0-9]', '', s)
    # Transforma em maiúsculas
    return s_sem_especiais.upper()

# Normalizar a coluna 'Nome'
pmqc['Município_Normalizado'] = pmqc['Município'].apply(normalizar_string)

print(pmqc['Município_Normalizado'])

0        ESTREITO
1        ESTREITO
2        ESTREITO
3        ESTREITO
4        ESTREITO
           ...
72933     GOIANIA
72934     GOIANIA
72935     GOIANIA
72936     GOIANIA
72937     GOIANIA
Name: Município_Normalizado, Length: 669776, dtype: object

In [33]:
nome_municipio_normalizado = 'UBERLANDIA'
status_conforme = 'Não'

municipio_filtrado = pmqc.loc[(pmqc['Município_Normalizado'] == nome_municipio_normalizado) & (pmqc['Conforme'] == status_conforme)]


print(municipio_filtrado)

Empty DataFrame
Columns: [DataColeta, IdNumeric, GrupoProduto, Produto, RazaoSocialPosto, CnpjPosto, Distribuidora, Endereço, Complemento, Bairro, Município, Latitude, Longitude, Uf, RegiaoPolitica, Ensaio, Resultado, UnidadeEnsaio, Conforme, Município_Normalizado]
Index: []

In [45]:
combustivel_carros = pmqc.query('GrupoProduto == "Gasolina"')

medicoes_por_linha = combustivel_carros.pivot(index='IdNumeric', columns='Categoria', values='Aspecto')

medicoes_por_linha.head()

KeyError: "None of ['Categoria'] are in the columns"

In [42]:
import pandas as pd

# Exemplo de DataFrame
dados = {'Nome': ['Alice', 'Bob', 'Charlie', 'Alice', 'Bob'],
         'Categoria': ['A', 'B', 'A', 'B', 'A'],
         'Valor': [10, 20, 30, 40, 50]}

df = pd.DataFrame(dados)

# Aplicar a função pivot
df_pivot = df.pivot(index='Nome', columns='Ensaio', values='Valor')

# Exibir o DataFrame original
print("DataFrame Original:")
print(df)

# Exibir o DataFrame pivotado
print("\nDataFrame Pivotado:")
print(df_pivot)

DataFrame Original:
      Nome Categoria  Valor
0    Alice         A     10
1      Bob         B     20
2  Charlie         A     30
3    Alice         B     40
4      Bob         A     50

DataFrame Pivotado:
Categoria     A     B
Nome
Alice      10.0  40.0
Bob        50.0  20.0
Charlie    30.0   NaN